name: ADK Answering Agent for Discussions

on:
  discussion:
    types: [created]

jobs:
  agent-answer-questions:
    if: github.event.discussion.category.name == 'Q&A'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.ADK_GCP_SA_KEY }}'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-adk google-cloud-discoveryengine

      - name: Run Answering Script
        env:
          GITHUB_TOKEN: ${{ secrets.ADK_TRIAGE_AGENT }}
          ADK_GCP_SA_KEY: ${{ secrets.ADK_GCP_SA_KEY }}
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          GOOGLE_CLOUD_LOCATION: ${{ secrets.GOOGLE_CLOUD_LOCATION }}
          VERTEXAI_DATASTORE_ID: ${{ secrets.VERTEXAI_DATASTORE_ID }}
          GEMINI_API_DATASTORE_ID: ${{ secrets.GEMINI_API_DATASTORE_ID }}
          GOOGLE_GENAI_USE_VERTEXAI: 1
          OWNER: 'google'
          REPO: 'adk-python'
          INTERACTIVE: 0
          PYTHONPATH: contributing/samples
          DISCUSSION_JSON: ${{ toJson(github.event.discussion) }}
        run: |
          # Replace single quotes with the sequence that allows them to be used in a single-quoted string
          # This replaces ' with '\'', which ends the current single-quoted string, adds an escaped single quote, then starts a new single-quoted string
          SAFE_JSON="${DISCUSSION_JSON//\'/\'\\\'\'}"
          python -m adk_answering_agent.main --discussion '$SAFE_JSON'
